"""empty message

Revision ID: 691fe57fc9a5
Revises: 
Create Date: 2022-05-25 04:06:40.352144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691fe57fc9a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

     op.execute('Update todos set completed=False where completed is null;')
     op.alter_column('todos','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
